# Generated by Django 4.1 on 2022-08-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='view_page',
            new_name='VeiwPage',
        ),
    ]
