# Generated by Django 4.1 on 2022-08-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_rename_view_page_veiwpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VeiwPage',
            new_name='Show',
        ),
    ]
