# Generated by Django 4.1 on 2022-09-18 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_viewpersonal_delete_view_personal'),
        ('show', '0003_rename_veiwpage_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='realat',
            field=models.ForeignKey(default=1111, on_delete=django.db.models.deletion.CASCADE, to='personal.viewpersonal'),
            preserve_default=False,
        ),
    ]
