# Generated by Django 4.1 on 2022-09-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_show_realat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='realat',
        ),
    ]
