# Generated by Django 4.1 on 2022-08-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_remove_view_personal_name_view_personal_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='view_personal',
            name='image',
            field=models.ImageField(default='none', upload_to=''),
        ),
    ]
